---
- name: ensure Vagrant with dependencies is installed
  dnf:
    name: "{{ item }}"
  with_items:
    - nfs-utils
    - vagrant
    - vagrant-libvirt
    - vagrant-libvirt-doc

- name: ensure no password is required for vagrant-libvirt
  shell: cp /usr/share/vagrant/gems/doc/vagrant-libvirt-*/polkit/10-vagrant-libvirt.rules /usr/share/polkit-1/rules.d/
  args:
    creates: /usr/share/polkit-1/rules.d/10-vagrant-libvirt.rules

- name: ensure sudoers file for Vagrant is installed
  copy:
    src: sudoers
    dest: /etc/sudoers.d/vagrant-commands
    owner: root
    group: root
    mode: 0600

- include: firewalld.yml
  when: vagrant_firewalld

- include: virtualbox.yml
  when: vagrant_virtualbox

- include: lxc.yml
  when: vagrant_lxc

- include: plugins.yml
