---
- name: ensure Vagrant with dependencies is installed
  package:
    name: "{{ item }}"
  with_items:
    - nfs-utils
    - vagrant

- name: ensure sudoers file for Vagrant is installed
  copy:
    src: sudoers
    dest: /etc/sudoers.d/vagrant-commands
    owner: root
    group: root
    mode: 0600

- include: firewalld.yml
  when: vagrant_firewalld

- include: libvirt.yml
  when: vagrant_libvirt

- include: virtualbox.yml
  when: vagrant_virtualbox

- include: lxc.yml
  when: vagrant_lxc

- include: plugin_packages.yml
  when: vagrant_plugin_packages

- include: plugins.yml
  when: vagrant_plugins
